# Generated by Django 4.2.6 on 2023-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to=''),
        ),
    ]
