# Generated by Django 4.2.6 on 2023-11-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'staff'), (3, 'student')], default=1, max_length=20),
        ),
    ]
