# Generated by Django 4.2.6 on 2023-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(3, 'student'), (2, 'staff'), (1, 'admin')], default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
