# Generated by Django 4.2.6 on 2023-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_adminprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default1.jpeg', null=True, upload_to=''),
        ),
    ]
