# Generated by Django 4.2.6 on 2023-11-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created']},
        ),
    ]
