# Generated by Django 4.2.6 on 2023-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_adminprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='mobile_number',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone_number',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
