# Generated by Django 4.2.6 on 2023-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_adminprofile_address_adminprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
