# Generated by Django 4.2.6 on 2023-11-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_user_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
