# Generated by Django 4.2.6 on 2023-10-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_adminprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
