# Generated by Django 4.2.6 on 2023-11-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='image_photo',
            new_name='profile_image',
        ),
    ]
