# Generated by Django 4.2.6 on 2023-11-05 15:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_studentprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentprofile',
            managers=[
                ('student_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
