# Generated by Django 4.2.6 on 2023-11-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
