# Generated by Django 4.2.6 on 2023-11-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentprofile',
            managers=[
            ],
        ),
    ]
