# Generated by Django 4.2.6 on 2023-11-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50, null=True),
        ),
    ]
