# Generated by Django 4.2.6 on 2023-11-18 00:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_studentuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentuser',
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], default='male', max_length=50, null=True),
        ),
    ]
