# Generated by Django 4.2.6 on 2023-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_studentuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50, null=True),
        ),
    ]
