# Generated by Django 4.2.6 on 2023-11-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_rename_mobile_number_adminprofile_mobile_and_more'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_type', models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('Admin.user',),
        ),
    ]
