# Generated by Django 4.2.6 on 2023-11-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], default='local', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
