# Generated by Django 4.2.6 on 2023-11-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_studentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
