# Generated by Django 4.2.6 on 2023-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], default='local', max_length=50),
        ),
    ]
