# Generated by Django 4.2.6 on 2023-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_delete_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_type', models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
