# Generated by Django 4.2.6 on 2023-11-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_studentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'F'), ('MALE', 'M')], max_length=255, null=True),
        ),
    ]
