# Generated by Django 4.2.6 on 2023-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_studentprofile_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50),
        ),
    ]
