# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_studentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50, null=True),
        ),
    ]
