# Generated by Django 4.2.6 on 2023-11-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], default='local', max_length=50),
        ),
    ]
