# Generated by Django 4.2.6 on 2023-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_studentprofile_user_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='student_type',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('LOCAL', 'local'), ('FOREIGNER', 'foreigner')], default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'student'), ('staff', 'staff')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='male', max_length=50),
        ),
    ]
