# Generated by Django 4.2.6 on 2023-11-01 18:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_remove_studentuser_student_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Students.studentuser',),
            managers=[
                ('staff', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Students.studentuser',),
            managers=[
                ('student', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('FOREIGNER', 'foreigner'), ('LOCAL', 'local')], default='local', max_length=50),
        ),
    ]
