# Generated by Django 4.2.6 on 2023-11-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_notificationstudent_notificationstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationStaff',
        ),
    ]
