# Generated by Django 4.2.6 on 2023-11-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_studentprofile_managers'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='StudentRegistration',
        ),
    ]
