# Generated by Django 4.2.6 on 2023-11-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_studentprofile_managers'),
        ('Student', '0002_rename_studentprofile_studentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.studentprofile'),
        ),
    ]
