# Generated by Django 4.2.6 on 2023-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_studentregistration_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'female'), ('MALE', 'male')], default='male', max_length=50),
        ),
    ]
