# Generated by Django 4.2.6 on 2023-11-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_studentprofile_managers'),
        ('Student', '0005_rename_name_studentregistration_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.studentprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='male', max_length=50),
        ),
    ]
